### ISSUE TITLE
wrong default Maven settings.xml

### ISSUE THREAD

**Issue by Ladicek** [fabric8io/fabric8-team-components#119]
This file https://github.com/fabric8io/fabric8-team-components/blob/master/jenkins-openshift/src/main/fabric8/jenkins-maven-settings-secret.yml contains what seems to be the current version of default Maven `settings.xml` file that is used in OpenShift.io. I believe this file contains major issues, and is actually the reason why WildFly Swarm boosters don't work on OpenShift.io.

For reference, here's the `base64 --decode` of the `settings.xml` value:

```xml
<settings>
  <!-- sets the local maven repository outside of the ~/.m2 folder for easier mounting of secrets and repo -->
  <localRepository>${user.home}/.mvnrepository</localRepository>
  <mirrors>
    <mirror>
      <id>nexus</id>
      <mirrorOf>external:*</mirrorOf>
      <url>http://central.maven.org/maven2/</url>
    </mirror>
    <mirror>
      <id>jboss</id>
      <mirrorOf>external:*</mirrorOf>
      <url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/</url>
    </mirror>
  </mirrors>

  <!-- lets disable the download progress indicator that fills up logs -->
  <interactiveMode>false</interactiveMode>

  <servers>
    <server>
      <id>local-nexus</id>
      <username>admin</username>
      <password>admin123</password>
    </server>
    <server>
      <id>nexus</id>
      <username>admin</username>
      <password>admin123</password>
    </server>
    <server>
      <id>oss-sonatype-staging</id>
      <username></username>
      <password></password>
    </server>
  </servers>

  <profiles>
    <profile>
      <id>nexus</id>
      <properties>
        <altDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altDeploymentRepository>
        <altReleaseDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altReleaseDeploymentRepository>
        <altSnapshotDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/snapshots/</altSnapshotDeploymentRepository>
      </properties>
      <repositories>
        <repository>
          <id>central</id>
          <url>http://central</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>central</id>
          <url>http://central</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
    <profile>
      <id>release</id>
      <properties>
        <gpg.executable>gpg</gpg.executable>
        <gpg.passphrase>mysecretpassphrase</gpg.passphrase>
      </properties>
    </profile>
  </profiles>
  <activeProfiles>
    <!--make the profile active all the time -->
    <activeProfile>nexus</activeProfile>
  </activeProfiles>
</settings>
```

I see two issues with that:

1. The `<mirrors>` section uses `<mirrorOf>external:*</mirrorOf>`, which basically means that no other Maven repository can be used. For example, the JBoss.org Public repo group is inaccessible. Why is it necessary to have those mirrors defined like this? Is it even necessary to predefine some mirrors? I'd remove that section completely.
2. Removing the mirrors section completely would expose another issue -- the `nexus` profile specifies `http://central` as a `<repository>` URL and also as a `<pluginRepository>` URL. This only works because of the mirror definitions using `<mirrorOf>external:*</mirrorOf>`. I don't really think it's necessary to define Maven Central as a `<repository>` and/or `<pluginRepository>`, Maven Central repositories are inherited from the Super POM. I'd remove this section completely as well.

I don't claim I understand the rest of the `settings.xml` configuration here, some of them seem really important (`<localRepository>`, ` <alt*DeploymentRepository>` and also probably the `local-nexus` server), but the definition of mirrors and repositories seems really off.

Thoughts?

**Comment by Ladicek** [comment]
I'd of course gladly submit a PR with my suggested changes, but I first want to understand if there's some deeper reason why the `settings.xml` looks like this.

**Comment by rawlingsj** [comment]
PRs are definitely welcome.  Currently I believe we're still able to oc edit secret `jenkins-maven-settings-secret` so you should be able to test out your suggestions on both the vertx and wildfly quickstarts to validate your thoughts and ensure it doesn't break existing quickstarts before submitting a PR.  No need to restart jenkins after making a change, just triggering a new build will start a build pod with the updated secret mounted into it.

This settings.xml has been around for ~3 years and used by fabric8 which also ships with Nexus.  rather than adding mirrors to the settings.xml we add repositories to Nexus so that does the repository management + dependency caching.

The section..
```
 <altDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altDeploymentRepository>
        <altReleaseDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altReleaseDeploymentRepository>
        <altSnapshotDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/snapshots/</altSnapshotDeploymentRepository>
```
Makes it easy to switch to using a Nexus or Artifactory for example.  I suspect we will move to that for OSIO in the future but for now as we cache dependencies on a PV you should be able to just add a JBoss mirror as you suggest.

**Comment by Ladicek** [comment]
I've verified that this has been fixed, though not in this repo (which is now deprecated) and I can't find where.
